spring.application.name=oauth-security

server.port=8081

# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=398412676907-lg2k1q57jto3j2j9irgdfcbaic97ai6s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Logging
logging.level.root=INFO
logging.level.com.example.oauthsecurity=DEBUG

# Log file
logging.file.name=logs/oauth-security.log

# Thymeleaf
spring.thymeleaf.cache=false